# Generated by Django 4.2.5 on 2023-10-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastUpdate', models.DateTimeField(blank=True, null=True)),
                ('NetworkSetting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NetworkConfiguration.networksetting')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPv4Address', models.GenericIPAddressField(blank=True, null=True)),
                ('IPv4SubnetMask', models.GenericIPAddressField(blank=True, null=True)),
                ('IPv4StandardGateway', models.GenericIPAddressField(blank=True, null=True)),
                ('Name', models.CharField(max_length=255)),
                ('AddressMode', models.CharField(blank=True, choices=[('Static', 'Static'), ('Automatic/DHCP', 'Automatic/DHCP')], max_length=255, null=True)),
                ('LinkSpeedReceiveTransmit', models.CharField(blank=True, max_length=255, null=True)),
                ('IPv4DNSServers', models.GenericIPAddressField(blank=True, null=True)),
                ('PrimaryDNSSuffix', models.CharField(blank=True, max_length=255, null=True)),
                ('network_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='NetworkConfiguration.networksetting')),
            ],
        ),
    ]
