# Generated by Django 4.2.5 on 2023-10-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPv4Address', models.GenericIPAddressField(blank=True, null=True)),
                ('IPv4SubnetMask', models.GenericIPAddressField(blank=True, null=True)),
                ('IPv4StandardGateway', models.GenericIPAddressField(blank=True, null=True)),
                ('HostName', models.CharField(blank=True, max_length=255, null=True)),
                ('AddressModus', models.CharField(blank=True, choices=[('Static', 'Static'), ('Automatic/DHCP', 'Automatic/DHCP')], max_length=255, null=True)),
                ('LinkSpeedReceiveTransmit', models.CharField(blank=True, max_length=255, null=True)),
                ('IPv4DNSServers', models.GenericIPAddressField(blank=True, null=True)),
                ('PrimaryDNSSuffix', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterfaceEth0', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceEth0', to='NetworkConfiguration.interface')),
                ('InterfaceEth1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceEth1', to='NetworkConfiguration.interface')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('NetworkSetting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NetworkConfiguration.networksetting')),
            ],
        ),
    ]
