# Generated by Django 4.2.5 on 2023-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfiguration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconfiguration',
            name='LastUpdate',
            field=models.DateTimeField(),
        ),
    ]
