# Generated by Django 4.2.5 on 2023-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkConfiguration', '0003_alter_networkconfiguration_lastupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='AddressModus',
            new_name='AddressMode',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='HostName',
            new_name='Name',
        ),
    ]
