# Generated by Django 4.2.5 on 2023-10-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPv4Address', models.GenericIPAddressField(protocol='IPv4')),
                ('NetworkMask', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('IPv4SubnetMask', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('Name', models.CharField(max_length=255)),
                ('LinkSpeedReceiveTransmit', models.CharField(blank=True, max_length=255, null=True)),
                ('LinkLocalIPv6Address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('IPv4DNSServers', models.CharField(blank=True, max_length=255, null=True)),
                ('PrimaryDNSSuffix', models.CharField(blank=True, max_length=255, null=True)),
                ('interface_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
