# Generated by Django 4.2.5 on 2023-10-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_remove_interface_linklocalipv6address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interface',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='interface_id',
        ),
        migrations.AddField(
            model_name='interface',
            name='LinkLocalIPv6Address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
        migrations.AddField(
            model_name='interface',
            name='NetworkMask',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='IPv4Address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='IPv4DNSServers',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='interface',
            name='name',
            field=models.CharField(default='InterfaceEth1', max_length=255),
        ),
        migrations.AddField(
            model_name='interface',
            name='network_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='interfaces.networksetting'),
        ),
    ]
