# Generated by Django 4.2.5 on 2023-10-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_networksetting_remove_interface_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='InterfaceEth1', max_length=255)),
                ('IPv4Address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('IPv4SubnetMask', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('LinkSpeedReceiveTransmit', models.CharField(blank=True, max_length=255, null=True)),
                ('IPv4DNSServers', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('PrimaryDNSSuffix', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interface',
            name='IPv4Address',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='IPv4DNSServers',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='IPv4SubnetMask',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='LinkLocalIPv6Address',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='LinkSpeedReceiveTransmit',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='NetworkMask',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='PrimaryDNSSuffix',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='network_setting',
        ),
        migrations.RemoveField(
            model_name='networksetting',
            name='name',
        ),
        migrations.AddField(
            model_name='networksetting',
            name='NetworkSetting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interfaces.interface'),
        ),
        migrations.AddField(
            model_name='interface',
            name='InterfaceEth0',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_eth0', to='interfaces.interfaceelements'),
        ),
        migrations.AddField(
            model_name='interface',
            name='InterfaceEth1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_eth1', to='interfaces.interfaceelements'),
        ),
    ]
