# Generated by Django 4.2.5 on 2023-10-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0004_interfaceelements_remove_interface_ipv4address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='InterfaceEth0',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceEth0', to='interfaces.interfaceelements'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='InterfaceEth1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceEth1', to='interfaces.interfaceelements'),
        ),
    ]
