# Generated by Django 4.2.5 on 2023-10-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0005_alter_interface_interfaceeth0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceelements',
            name='Name',
        ),
        migrations.AddField(
            model_name='interfaceelements',
            name='AddressModus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interfaceelements',
            name='HostName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interfaceelements',
            name='IPv4StandardGateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceelements',
            name='IPv4Address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceelements',
            name='IPv4DNSServers',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interfaceelements',
            name='IPv4SubnetMask',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
