# Generated by Django 4.2.5 on 2023-10-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0006_remove_interfaceelements_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceelements',
            name='AddressModus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
