# Generated by Django 4.2.5 on 2023-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0007_alter_interfaceelements_addressmodus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfaceelements',
            old_name='AddressModus',
            new_name='AddressMode',
        ),
        migrations.RenameField(
            model_name='interfaceelements',
            old_name='HostName',
            new_name='Name',
        ),
    ]
