# Generated by Django 4.2.5 on 2023-10-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardTemperature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAMInstalled', models.CharField(blank=True, max_length=255, null=True)),
                ('RAMFree', models.CharField(blank=True, max_length=255, null=True)),
                ('DiskInstalled', models.CharField(blank=True, max_length=255, null=True)),
                ('DiskFree', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CpuType', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuCores', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuClock', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuUsage', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuTemperature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HealthStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('LastUpdate', models.DateTimeField()),
                ('Hardware', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SystemInformation.hardware')),
            ],
        ),
        migrations.AddField(
            model_name='hardware',
            name='Memory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SystemInformation.memory'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='Processor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SystemInformation.processor'),
        ),
    ]
