# Generated by Django 4.2.5 on 2023-10-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAMInstalled', models.CharField(blank=True, max_length=255, null=True)),
                ('RAMFree', models.CharField(blank=True, max_length=255, null=True)),
                ('DiskInstalled', models.CharField(blank=True, max_length=255, null=True)),
                ('DiskFree', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CpuType', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuCores', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuClock', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuUsage', models.CharField(blank=True, max_length=255, null=True)),
                ('CpuTemperature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoardTemperature', models.CharField(blank=True, max_length=255, null=True)),
                ('Memory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.memoryelements')),
                ('Processor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.processorelements')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hardware', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwareelements')),
            ],
        ),
    ]
